# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ponds-forge-lane-swimming-lambda

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  stage: prod
  region: eu-west-2

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# We use browserify to produce a single JS file in the dist/ folder.
# So ignore all source files and node_module packages.
package:
  exclude:
    - index.js
    - lib/**
    - node_modules/**

functions:
  laneSwimmingData:
    handler: dist/index.laneSwimmingDataHandler
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: /laneSwimmingData
          method: get
          cors: true
  pondsForgeLaneSwimmingData:
    handler: dist/index.pondsForgeLaneSwimmingDataHandler
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: /pondsForgeLaneSwimmingData
          method: get
          cors: true
  s10LaneSwimmingData:
    handler: dist/index.s10LaneSwimmingDataHandler
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: /s10LaneSwimmingData
          method: get
          cors: true
